# Generated by Django 4.1.5 on 2023-02-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="defaults/default.jpg", upload_to="userprofile"
            ),
        ),
    ]
